version: '3'
services:
    app:
        build:
            args:
                user: tracker
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: realtracker:1.0.1
        container_name: realtracker-app        
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - realtracker
        environment:
          PROXY_SCHEME: "https"
#          APP_URL: "https://realtracker.dsplab.ru"


    db:
        image: 'mysql/mysql-server:8.0'
        container_name: realtracker-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_USER: '${DB_USERNAME}'
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
            - ./docker-compose/mysql/db:/var/lib/mysql
        networks:
            - realtracker

    nginx:
        image: nginx:alpine
        container_name: realtracker-nginx
        restart: unless-stopped
        #ports:
        #    - 80:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - realtracker
            - extnet
networks:
    realtracker:
        driver: bridge
    extnet:
        external: true

