cgi.fix_pathinfo=0

post_max_size = 100M
upload_max_filesize = 100M
variables_order = EGPCS
pcov.directory = .

max_execution_time = 1000
max_input_time = 1000

output_buffering=4096
log_errors = On

cgi.fix_pathinfo = 1

display_errors = off
display_startup_errors = off
enable_dl= off
expose_php= off
max_execution_time= 30
max_input_time=60
post_max_size=8M
register_argc_argv= off
request_order=GP
short_open_tag=off
upload_max_filesize=2M
zend.assertions=-1
zend.exception_ignore_args=on
zend.exception_string_param_max_len=0

ffi.enable=preload
pdo_mysql.default_socket=/var/run/mysqld/mysqld.sock