# HTTP -> HTTPS
server {
    listen 80;
    server_name tracker.ntc _;

    return 301 https://$host$request_uri;
}

server {
    fastcgi_buffers 16 32k;
    fastcgi_buffer_size 64k;

    listen 443 ssl;
    server_name tracker.ntc;

    ssl_certificate     /etc/nginx/certs/tracker.ntc.crt;
    ssl_certificate_key /etc/nginx/certs/tracker.ntc.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    error_log  /var/log/nginx/app.error.log;
    access_log /var/log/nginx/app.access.log;

    client_max_body_size 100M;

    root /var/www/public;
    index index.php index.html;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    location /build {
        try_files $uri =404;
        expires 30d;
        add_header Cache-Control "public";
    }
}
